SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY;

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY (CATAGORY_NAME)
VALUES ('MalE');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY (CATAGORY_NAME)
VALUES ('Female');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY (CATAGORY_NAME)
VALUES ('Urban');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY (CATAGORY_NAME)
VALUES ('Rural');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY (CATAGORY_NAME)
VALUES ('TOTAL');
	
