SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES;

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Belarus');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Central African Republic');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Chad');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Democratic Republic of Cangro');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Central African Republic');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Gambia');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Ghana');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Central African Republic');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Guinea-Bissau');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Guyana');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Iraq');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Kiribati');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Kosovo');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Kyrgystan');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Lesotho');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Madagascar');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Mangolia');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Nepal');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('North Mecedonia');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('State of Palestine');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Pakistan');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Samoa');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Sao Tome and Principe');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Sierra Leone');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Suriname');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Turks and Caicos Island');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Togo');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Tunisia');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Turkmenistan');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Tuvalu');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES (COUNTRY_NAME)
VALUES ('Zimbabwe');