SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE;

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS6');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS7');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS8');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS9');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS10');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DATA_SOURCE(DATA_SOURCE_NAME)
VALUES
('MICS11');
