/*
---> ER MODELING
---> QUERY THE DATA
*/

SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES;
/*QUERING CATAGORY BASED ON KEYWORD FMALE*/
SELECT CATAGORY_ID, CATAGORY_NAME FROM GLOBAL_DATABASE_CHILDER_EDUCATION.CATAGORY
WHERE CATAGORY_NAME = 'FEMALE';

/*ARRANGING COUNTRY NAME BY ASCENDING ORDER*/
SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES
ORDER BY COUNTRY_NAME ASC;

/*ARRANGING COUNTRY NAME BY DESCENDING ORDER*/
SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES
ORDER BY COUNTRY_NAME DESC;

/*FETCHING COUNTRIES NAME START WITH G*/
SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES
WHERE COUNTRY_NAME LIKE'G%';

/*
COUNTING TOTAL NUMBER OF COUNTRIES USING COUNT()
*/
SELECT COUNT(COUNTRY_NAME)
FROM GLOBAL_DATABASE_CHILDER_EDUCATION.COUNTRIES;

/*
CALCULATING AVERAGE NUMBER OF UNICEF_POINT AVG()
*/
SELECT COUNT(CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES)
FROM GLOBAL_DATABASE_CHILDER_EDUCATION.UNICEF_ID
;

/*
COUNTING ISO_CODE BASED ON CATAGORIES USING GROUP BY 
*/
SELECT COUNT(CATAGORY_ID), ISO_CODE
FROM GLOBAL_DATABASE_CHILDER_EDUCATION.UNICEF_ID
GROUP BY ISO_CODE;

/*
TABLE UNICEF_ID CONTAINS FOLLOWING FOREIGN KEYS (COUNTRY_ID, DEVELOPMENT_ID, CATOGORY_ID, SOURSE_ID, REGION_ID)
USING JOINS
*/
SELECT  
		UID.ISO_CODE,
		UID.CHILDERN_WITH_FUNCTIONAL_DISABILITIES,
        UID.CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES,
		COU.COUNTRY_NAME,
        DS.DEVELOPMENT_STATUS,
        CAT.CATAGORY_NAME,
        DDS.DATA_SOURCE_NAME,
        REG.REGION_NAME
FROM GLOBAL_DATABASE_CHILDER_EDUCATION.UNICEF_ID UID
JOIN COUNTRIES COU ON COU.COUNTRY_ID = UID.COUNTRY_ID
JOIN DEVELOPMENT_STATUS DS ON DS.DEVELOPMENT_ID = UID.DEVELOPMENT_ID
JOIN CATAGORY CAT ON CAT.CATAGORY_ID = UID.CATAGORY_ID
JOIN DATA_SOURCE DDS ON DDS.SOURCE_ID = UID.SOURCE_ID
JOIN REGION REG ON REG.REGION_ID = UID.REGION_ID
;

        


