SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.DEVELOPMENT_STATUS;

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DEVELOPMENT_STATUS(DEVELOPMENT_STATUS)
VALUES
('Less Developed');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DEVELOPMENT_STATUS(DEVELOPMENT_STATUS)
VALUES
('Least Developed');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.DEVELOPMENT_STATUS(DEVELOPMENT_STATUS)
VALUES
('MORE_DEVELOP');