SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.REGION;

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('SA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('EECA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('SSA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('LAC');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('MENA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('EAP');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('ECA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('EAP');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('EECA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('MENA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('WCA');

INSERT INTO GLOBAL_DATABASE_CHILDER_EDUCATION.REGION(REGION_NAME)
VALUES
('ESA');

