SELECT * FROM GLOBAL_DATABASE_CHILDER_EDUCATION.UNICEF_ID;

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('BGD', '83.7', '69.6', '1', '5002', '10000', '1', '1');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('BLR', '93.2', '91.2', '2', '5003', '10003', '1', '2');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('CAF', '73.2', '71.2', '2', '5003', '10003', '1', '3');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('CAF', '73.2', '71.2', '2', '5003', '10003', '1', '3');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('IRQ', '77.2', '76.7', '12', '5001', '10002', '4', '11');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('NPL', '74.2', '73.7', '19', '5000', '10004', '6', '1');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('WSM', '89.2', '88.7', '23', '5000', '10003', '3', '8');

INSERT INTO `GLOBAL_DATABASE_CHILDER_EDUCATION`.`UNICEF_ID` 
(`ISO_CODE`, `CHILDERN_WITH_FUNCTIONAL_DISABILITIES`, `CHILDERN_WITHOUT_FUNCTIONAL_DISABILITIES`, `COUNTRY_ID`, `DEVELOPMENT_ID`, `CATAGORY_ID`, `SOURCE_ID`, `REGION_ID`) 
VALUES ('TUV', '71.9', '72.4', '31', '5002', '10004', '6', '6');
